### PR TITLE
Issue #297 Add Arch Linux host support

### LINKED ISSUE #297: Support Arch Linux as host
Add "caps" to install dnsmasq with *pacman*.

### PR DESCRIPTION
**Pull request by njam**
Closes #297

### CODE REVIEW

**Comment by hferentschik** [comment]
Nice, do we have an issue for this as well? I think there is an issue with the Travis CI config as well. I have an idea what it is. Looking into it.

**Comment by njam** [comment]
The problem is that we rely on vagrant 1.8.6 which requires bundler 1.12.5, but travis now has 1.13.6.
I think the best resolution is to [upgrade to vagrant 1.9.0](https://github.com/vagrant-landrush/landrush/pull/296) which removes the bundler requirement completely.

**Comment by hferentschik** [comment]
> The problem is that we rely on vagrant 1.8.6 which requires bundler 1.12.5, but travis now has 1.13.6.

Right, I fixed that. 

> I think the best resolution is to upgrade to vagrant 1.9.0 which removes the bundler requirement completely.

Sure. Let's do that after the release. Current trunk contains several changes which are useful and it also takes users up to Vagrant 1.8.6. Then as you say, for Vagrant 1.9 we need a new plan. TBH, I have not yet looked into the changes Vagrant 1.9 brings. On my todo list. I guess I will start with your pull requests ;-)

**Comment by njam** [comment]
Agree!

The build succeeds now.
I think this should be ready.

**Comment by hferentschik** [comment]
Merged, thanks (squashed the commits)

**Pull request closed without merging**
