### PR TITLE
Issue #295 Vagrant 1.9 compatibility

### PR DESCRIPTION
**Pull request by njam**
Addressing #295

Instead of running the DNS server with `ruby start_server.rb 10053 --gem_path=~/.vagrant.d/gems/gems`  we could start it as a plugin command:
```
vagrant landrush run-server 10053
```

This way we can avoid passing the gems directory along, because vagrant sets all of that up for us.

wdyt?

### CODE REVIEW

**Comment by hferentschik** [comment]
> This way we can avoid passing the gems directory along, because vagrant sets all of that up for us.

Interesting idea. I need to look a bit closer at this. There seems to be some issues with the tests on Windows though.

**Comment by njam** [comment]
It seems like `vagrant` is not on the PATH (is it the right term?) on this [Windows build](https://ci.appveyor.com/project/hferentschik/landrush-3agrx/build/24). Do you know what is the best course of action?

**Comment by hferentschik** [comment]
> Do you know what is the best course of action?

Not out of the top of my head. If it is really just a PATH issue, we can just make sure vagrant is added to the PATH. One would expect though that it is. I guess I would like to know why it is not on the PATH first. Give me a few days to look into this. I am a bit swamped with other things right now, but hopefully I get a bit of time over the next days to look into this.

**Comment by thor** [comment]
Anyone mind if I poke this issue to see what its status is? :)

**Comment by robertoschwald** [comment]
Any news on this? Is this repo maintained anymore?

**Comment by ezekg** [comment]
I'm embedding Landrush/Vagrant into a desktop app (essentially a GUI for Vagrant) and ended up having to include this script which runs after updating Vagrant to latest:

```bash
#!/bin/bash

# Fix compatibility issues with Vagrant >= 1.9.2 and Landrush 1.2.0
if [[ -L ~/.vagrant.d/gems/gems && -d ~/.vagrant.d/gems/gems ]]; then
  echo "already symlinked"
else
  echo "creating symlink"
  mkdir -p ~/.vagrant.d/gems/2.2.5/gems
  mkdir -p ~/.vagrant.d/gems/gems
  mv -f ~/.vagrant.d/gems/gems/* ~/.vagrant.d/gems/2.2.5/gems/ 2>&1 > /dev/null
  rm -r ~/.vagrant.d/gems/gems
  ln -sf ~/.vagrant.d/gems/2.2.5/gems ~/.vagrant.d/gems/gems 2>&1 > /dev/null
  echo "symlink created"
fi

# Install required plugins (just to be safe)
vagrant plugin install landrush --plugin-version 1.2.0
# … other plugins

# Attempt to repair existing plugins
vagrant plugin expunge --reinstall --force
```

The app also includes an embedded Ruby (2.2.5) so you may need to change that if you're running a different version of Ruby locally.

**Comment by hferentschik** [comment]
I am going to close this pull request. I am not generally opposed to this, but as part of issue #324 Landrush already upgraded to Vagrant 2.1.2. AFAICT everything works fine. 

I can see that the proposed change makes things a bit easier since we let Vagrant deal with setting up the various paths. At the same time, it relies on vagrant being on the PATH. In most cases that might be the case, but not always (see the AppVeyor).

Regarding the problem which occurred when the gem path changed, the server start script worked as expected. However, due to the change one either needed to delete _~/.vagrant.d_ or do a reinstall of the plugin.

**Pull request closed without merging**
