### PR TITLE
Issue #321 Adding enable_route_localnet guest capability

### PR DESCRIPTION
**Pull request by hferentschik**
- Aligning some info messages format

Fix for issue #321

### CODE REVIEW

**Comment by hferentschik** [comment]
@ianmiell, what do you think about this? I had a crack at this issue. I don't think one really has to use the capabilities mechanism here, but I wanted to stick to the theme. WDYT?

**Comment by ianmiell** [comment]
I'm afraid I ran out of time, and now work somewhere where I've not got
permission to contribute (and have less spare time). If memory serves I
thought caps might be a bit overkilll.

**Comment by hferentschik** [comment]
> I'm afraid I ran out of time, and now work somewhere where I've not got
> permission to contribute (and have less spare time).

no worries

> If memory serves I thought caps might be a bit overkilll

Sure, it is probably not required. Definitely works without as well. I am a bit undecided on this one. The main reason to go with this approach was to stick with the existing structure of the code. As it stands now, the existing linux capabilities could be combined. The advantage would probably be a more compact and less indirect code. I don't think that using capabilities is otherwise a performance issues or similar. The advantage of the capabilities is that in the case one needs at some stage to differentiate  for any of these actions between different Linux distributions, one can easily do so. 

Given that the current pull request works, I am wondering whether it makes sense to merge it. Then in a follow up issue one could decide whether one would like to combine the existing Linux capabilities.

**Comment by tristanbes** [comment]
Hello,

Since this patch is required to be able to use landrush with 18.04, is that possible you tag a version please ? @hferentschik

**Pull request merged**
