### PR TITLE
Issue #176 Create no more reverse entry for cname static dns entries

### LINKED ISSUE #176: Can't create cname in Vagrantfile
this works...

`system("vagrant landrush set #{hostalias} #{hostname})`

this does not work...

`config.landrush.host hostalias, hostname`

the following error is produced...

```
/opt/vagrant/embedded/lib/ruby/2.2.0/ipaddr.rb:559:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/ipaddr.rb:496:in `initialize'
	from /home/vagrant/.vagrant.d/gems/gems/landrush-0.19.0/lib/landrush/action/setup.rb:66:in `new'
	from /home/vagrant/.vagrant.d/gems/gems/landrush-0.19.0/lib/landrush/action/setup.rb:66:in `block in setup_static_dns'
	from /home/vagrant/.vagrant.d/gems/gems/landrush-0.19.0/lib/landrush/action/setup.rb:61:in `each'
```

### PR DESCRIPTION
**Pull request by Valgard**
fixes #176

### CODE REVIEW

**Comment by hferentschik** [comment]
Awesome, thank you for the pull request. I am looking into it asap.

**Comment by hferentschik** [comment]
Superseded by pull request #207. @Valgard, I took your patch and added some tests and made the logic a bit more explicit. Thanks for helping out

**Comment by Valgard** [comment]
Thanks. I'm not so confirmed in ruby. ;)

**Comment by hferentschik** [comment]
> Thanks. I am not so knowledgeable in Ruby. ;)

No worries. Just the fact that you already pin pointed the problem helped. Just needed to add more tests ;-). A fix will be available in Landrush 1.1.0 which will be out soon

**Pull request closed without merging**
